
set(FILES
        Include/ROSConDemo/ROSConDemoBus.h
        Source/ApplePicker/ApplePickerComponent.cpp
        Source/ApplePicker/ApplePickerComponent.h
        Source/ApplePicker/ApplePickingNotifications.h
        Source/ApplePicker/ApplePickingRequests.h
        Source/ApplePicker/PickingStructs.h
        Source/ApplePicker/KrakenEffectorComponent.cpp
        Source/ApplePicker/KrakenEffectorComponent.h
        Source/FruitStorage/FruitStorageComponent.cpp
        Source/FruitStorage/FruitStorageComponent.h
        Source/FruitStorage/FruitStorageBus.h
        Source/ApplePicker/ManipulatorRequestBus.cpp
        Source/ApplePicker/ManipulatorRequestBus.h
        Source/ROSConDemoSystemComponent.cpp
        Source/ROSConDemoSystemComponent.h
        enabled_gems.cmake
        )
