
set(FILES
        Include/ROSConDemo/ROSConDemoBus.h
        Source/ApplePicker/AppleDetectionGroundTruth.cpp
        Source/ApplePicker/AppleDetectionGroundTruth.h
        Source/ApplePicker/ApplePickerComponent.cpp
        Source/ApplePicker/ApplePickerComponent.h
        Source/ApplePicker/ApplePickingNotifications.h
        Source/ApplePicker/ApplePickingRequests.h
        Source/ApplePicker/GatheringRowComponent.cpp
        Source/ApplePicker/GatheringRowComponent.h
        Source/ApplePicker/GatheringRowRequests.h
        Source/ApplePicker/KrakenEffectorComponent.cpp
        Source/ApplePicker/KrakenEffectorComponent.h
        Source/ApplePicker/PickingStructs.h
        Source/DemoStatistics/AppleEvent.h
        Source/DemoStatistics/DemoStatisticsComponent.cpp
        Source/DemoStatistics/DemoStatisticsComponent.h
        Source/DemoStatistics/DemoStatisticsNotifications.h
        Source/FruitStorage/FruitStorageComponent.cpp
        Source/FruitStorage/FruitStorageComponent.h
        Source/FruitStorage/FruitStorageBus.h
        Source/KrakenCamera/FollowingCameraComponent.cpp
        Source/KrakenCamera/FollowingCameraComponent.h
        Source/Manipulator/KrakenManipulatorController.cpp
        Source/Manipulator/KrakenManipulatorController.h
        Source/Manipulator/ManipulatorRequestBus.h
        Source/ROSConDemoModuleInterface.h
        Source/ROSConDemoSystemComponent.cpp
        Source/ROSConDemoSystemComponent.h
        enabled_gems.cmake
        )
